jobs:
  cleanup-nightly-docs:
    if: github.event.ref_type == 'branch'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        DELETED_BRANCH: ${{ github.event.ref }}
      id: configuration
      name: Configure workflow
      run: 'BRANCH_NAME="${DELETED_BRANCH#refs/*/}"

        echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_OUTPUT

        echo "DOCS_OUTPUT_DIR=${GITHUB_WORKSPACE}/skript-docs/docs/nightly/${BRANCH_NAME}"
        >> $GITHUB_OUTPUT

        echo "DOCS_REPO_DIR=${GITHUB_WORKSPACE}/skript-docs" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Checkout Skript
      uses: actions/checkout@v4
      with:
        path: skript
        ref: ${{ github.event.repository.default_branch }}
        submodules: recursive
    - continue-on-error: true
      name: Setup documentation environment
      uses: ./skript/.github/workflows/docs/setup-docs
      with:
        docs_deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
        docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
    - continue-on-error: true
      env:
        DOCS_OUTPUT_DIR: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
      name: Cleanup nightly documentation
      run: 'rm -rf ${DOCS_OUTPUT_DIR} || true

        '
    - continue-on-error: true
      name: Push nightly documentation cleanup
      uses: ./skript/.github/workflows/docs/push-docs
      with:
        docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
        git_commit_message: Delete ${{ steps.configuration.outputs.BRANCH_NAME }}
          branch nightly docs
        git_email: nightlydocs@skriptlang.org
        git_name: Nightly Docs Bot
name: Cleanup nightly documentation
on:
  repository_dispatch:
    types: trigger-ga___cleanup-docs.yml
