jobs:
  build:
    if: '! contains(toJSON(github.event.commits.*.message), ''[ci skip]'')'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - continue-on-error: true
      name: validate gradle wrapper
      uses: gradle/wrapper-validation-action@v2
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        cache: gradle
        distribution: adopt
        java-version: '17'
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Build Skript and run JUnit
      run: ./gradlew clean JUnitJava8
name: JUnit (MC 1.13-1.16)
on:
  repository_dispatch:
    types: trigger-ga___junit-8-builds.yml
