jobs:
  nightly-docs:
    if: '!contains(toJSON(github.event.commits.*.message), ''[ci skip]'')'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        DOCS_DEPLOY_KEY: ${{ secrets.DOCS_DEPLOY_KEY }}
      id: configuration
      name: Configure workflow
      run: "if [ -n \"$DOCS_DEPLOY_KEY\" ]\nthen\n  echo \"DOCS_DEPLOY_KEY_PRESENT=true\"\
        \ >> $GITHUB_OUTPUT\nelse\n  echo \"Secret 'DOCS_DEPLOY_KEY' not present.\
        \ Exiting job.\"\nfi\nBRANCH_NAME=\"${GITHUB_REF#refs/*/}\"\necho \"BRANCH_NAME=${BRANCH_NAME}\"\
        \ >> $GITHUB_OUTPUT\necho \"DOCS_OUTPUT_DIR=${GITHUB_WORKSPACE}/skript-docs/docs/nightly/${BRANCH_NAME}\"\
        \ >> $GITHUB_OUTPUT\necho \"DOCS_REPO_DIR=${GITHUB_WORKSPACE}/skript-docs\"\
        \ >> $GITHUB_OUTPUT\necho \"SKRIPT_REPO_DIR=${GITHUB_WORKSPACE}/skript\" >>\
        \ $GITHUB_OUTPUT\n"
    - continue-on-error: true
      name: Checkout Skript
      uses: actions/checkout@v4
      with:
        path: skript
        submodules: recursive
    - continue-on-error: true
      if: steps.configuration.outputs.DOCS_DEPLOY_KEY_PRESENT == 'true'
      name: Setup documentation environment
      uses: ./skript/.github/workflows/docs/setup-docs
      with:
        docs_deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
        docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
    - continue-on-error: true
      id: generate
      if: steps.configuration.outputs.DOCS_DEPLOY_KEY_PRESENT == 'true'
      name: Generate documentation
      uses: ./skript/.github/workflows/docs/generate-docs
      with:
        docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
        docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
        skript_repo_dir: ${{ steps.configuration.outputs.SKRIPT_REPO_DIR }}
    - continue-on-error: true
      if: steps.generate.outputs.DOCS_CHANGED == 'true'
      name: Push nightly documentation
      uses: ./skript/.github/workflows/docs/push-docs
      with:
        docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
        git_commit_message: Update ${{ steps.configuration.outputs.BRANCH_NAME }}
          branch nightly docs to ${{ github.repository }}@${{ github.sha }}
        git_email: nightlydocs@skriptlang.org
        git_name: Nightly Docs Bot
name: Nightly documentation
on:
  repository_dispatch:
    types: trigger-ga___nightly-docs.yml
