jobs:
  archive-docs:
    if: '! contains(toJSON(github.event.commits.*.message), ''[ci skip]'')'
    needs: release-docs
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: configuration
      name: Configure workflow
      run: 'echo "BRANCH_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

        echo "DOCS_OUTPUT_DIR=${GITHUB_WORKSPACE}/skript-docs/docs/archives/${GITHUB_REF#refs/tags/}"
        >> $GITHUB_OUTPUT

        echo "DOCS_REPO_DIR=${GITHUB_WORKSPACE}/skript-docs" >> $GITHUB_OUTPUT

        echo "SKRIPT_REPO_DIR=${GITHUB_WORKSPACE}/skript" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Checkout Skript
      uses: actions/checkout@v4
      with:
        path: skript
        submodules: recursive
    - continue-on-error: true
      name: Setup documentation environment
      uses: ./skript/.github/workflows/docs/setup-docs
      with:
        docs_deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
        docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
    - continue-on-error: true
      name: Generate documentation
      uses: ./skript/.github/workflows/docs/generate-docs
      with:
        docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
        docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
        is_release: true
        skript_repo_dir: ${{ steps.configuration.outputs.SKRIPT_REPO_DIR }}
    - continue-on-error: true
      name: Push archive documentation
      uses: ./skript/.github/workflows/docs/push-docs
      with:
        docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
        git_commit_message: Update ${{ steps.configuration.outputs.BRANCH_NAME }}
          archive docs
        git_email: archivedocs@skriptlang.org
        git_name: Archive Docs Bot
  release-docs:
    if: '! contains(toJSON(github.event.commits.*.message), ''[ci skip]'')'
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: configuration
      name: Configure workflow
      run: 'echo "BRANCH_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

        echo "DOCS_OUTPUT_DIR=${GITHUB_WORKSPACE}/skript-docs/docs/" >> $GITHUB_OUTPUT

        echo "DOCS_REPO_DIR=${GITHUB_WORKSPACE}/skript-docs" >> $GITHUB_OUTPUT

        echo "SKRIPT_REPO_DIR=${GITHUB_WORKSPACE}/skript" >> $GITHUB_OUTPUT

        '
    - continue-on-error: true
      name: Checkout Skript
      uses: actions/checkout@v4
      with:
        path: skript
        submodules: recursive
    - continue-on-error: true
      name: Setup documentation environment
      uses: ./skript/.github/workflows/docs/setup-docs
      with:
        docs_deploy_key: ${{ secrets.DOCS_DEPLOY_KEY }}
        docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
    - continue-on-error: true
      name: Generate documentation
      uses: ./skript/.github/workflows/docs/generate-docs
      with:
        cleanup_pattern: '!(nightly|archives|templates)'
        docs_output_dir: ${{ steps.configuration.outputs.DOCS_OUTPUT_DIR }}
        docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
        is_release: true
        skript_repo_dir: ${{ steps.configuration.outputs.SKRIPT_REPO_DIR }}
    - continue-on-error: true
      name: Push release documentation
      uses: ./skript/.github/workflows/docs/push-docs
      with:
        docs_repo_dir: ${{ steps.configuration.outputs.DOCS_REPO_DIR }}
        git_commit_message: Update release docs to ${{ steps.configuration.outputs.BRANCH_NAME
          }}
        git_email: releasedocs@skriptlang.org
        git_name: Release Docs Bot
name: Release documentation
on:
  repository_dispatch:
    types: trigger-ga___release-docs.yml
